# Generated by Django 4.2.9 on 2025-04-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
    ]
