# Generated by Django 4.2.9 on 2025-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Availability for appointments'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, help_text="Doctor's medical license number", max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('GENERAL_MEDICINE', 'MD General Medicine'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPEDIC', 'Orthopedic'), ('ONCOLOGY', 'Oncology')], max_length=20),
        ),
    ]
