# Generated by Django 4.2.9 on 2025-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_available_user_license_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='license_number',
            new_name='doctor_license_number',
        ),
        migrations.AddField(
            model_name='user',
            name='nurse_license_number',
            field=models.CharField(blank=True, help_text="Nurse's license number", max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nursing_specialty',
            field=models.CharField(blank=True, help_text='Nursing specialty (e.g., ICU, ER)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacist_license_number',
            field=models.CharField(blank=True, help_text="Pharmacist's license number", max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_certification',
            field=models.CharField(blank=True, help_text='Pharmacy certification (e.g., PharmD)', max_length=100),
        ),
    ]
