# Generated by Django 4.2.9 on 2025-04-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_license_number_user_doctor_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique employee ID', max_length=10, null=True),
        ),
    ]
