# Generated by Django 4.2.9 on 2025-04-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_employee_id'),
    ]

    operations = [
    ]
