# Generated by Django 4.2.9 on 2026-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_head_nurse',
            field=models.BooleanField(default=False, help_text='Head nurse: can manage the hospital inventory'),
        ),
    ]
