# Generated by Django 5.2 on 2025-06-25 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('general', 'General Medicine'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('preferred_date', models.DateField()),
                ('health_records', models.FileField(blank=True, null=True, upload_to='health_records/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('SCHEDULED', 'Scheduled'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for receptionist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appointment Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
