# Generated by Django 5.2 on 2025-06-25 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20250625_2353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentinquiry',
            name='preferred_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentinquiry',
            name='department',
            field=models.CharField(choices=[('general_medicine', 'General Medicine MD'), ('cardiology', 'Cardiologist'), ('orthopedics', 'Orthopedic'), ('neurology', 'Neurologist'), ('oncology', 'Cancer')], max_length=50),
        ),
    ]
