# Generated by Django 5.2 on 2025-06-25 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_appointmentinquiry_preferred_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(help_text='Brief description of the blog post', max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(choices=[('HEALTH_TIPS', 'Health Tips'), ('MEDICAL_NEWS', 'Medical News'), ('TREATMENT_UPDATES', 'Treatment Updates'), ('RESEARCH', 'Medical Research'), ('WELLNESS', 'Wellness & Prevention'), ('TECHNOLOGY', 'Medical Technology'), ('PATIENT_CARE', 'Patient Care'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post on the homepage')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
