# Generated by Django 5.2 on 2025-06-27 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blogcomment_blogsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('message_body', models.TextField()),
                ('message_id', models.CharField(help_text='Email Message-ID to prevent duplicates', max_length=200, unique=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_seen_by_staff', models.BooleanField(default=False)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal staff notes about this reply', null=True)),
                ('raw_email_headers', models.JSONField(blank=True, help_text='Raw email headers for debugging', null=True)),
                ('email_received_at', models.DateTimeField(help_text='When the email was actually received')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='When we processed the email')),
                ('related_appointment_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_replies', to='website.appointmentinquiry')),
                ('related_contact_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_replies', to='website.contactinquiry')),
            ],
            options={
                'verbose_name_plural': 'Email Replies',
                'ordering': ['-email_received_at'],
            },
        ),
    ]
