# Generated by Django 4.2.9 on 2026-07-11 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_admissionrequest_preferred_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0002_supplier_country_supplier_representative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Clinical reason / note for the request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('response_notes', models.TextField(blank=True)),
                ('approved_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity approved/dispensed by pharmacy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drug_requests', to='pharmacy.medicineitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_requests', to='patient.patient')),
                ('requesting_nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='drug_requests', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'PHARMACIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_request_responses', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_requests', to='pharmacy.sale')),
            ],
            options={
                'verbose_name': 'Drug Request',
                'verbose_name_plural': 'Drug Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pharmacy_dr_status_0748bb_idx')],
            },
        ),
    ]
