# Generated by Django 4.2.9 on 2026-07-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_drugrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugrequest',
            name='sale',
        ),
    ]
