# Generated by Django 4.2.9 on 2025-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_doctorleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency appointments are available 24/7'),
        ),
    ]
