# Generated by Django 4.2.9 on 2025-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g., 120/80 mmHg', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_test_results',
            field=models.TextField(blank=True, help_text='Results of any blood tests performed'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sugar_level',
            field=models.CharField(blank=True, help_text='Blood glucose level', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='Detailed treatment plan'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='xray_image',
            field=models.ImageField(blank=True, help_text='Upload X-ray images if available', null=True, upload_to='medical_records/xrays/'),
        ),
    ]
