# Generated by Django 4.2.9 on 2025-04-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_medicalrecord_blood_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('last_sanitized', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['room', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('specialization', models.CharField(choices=[('CANCER', 'Cancer Specialists (4th & 5th Floor)'), ('MEDICINE', 'MD General Medicine (1st Floor)'), ('ORTHOPEDIC', 'Orthopedic (2nd Floor)'), ('CARDIOLOGY', 'Cardiologist (3rd Floor)')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('admission_type', models.CharField(choices=[('REGULAR', 'Regular Admission'), ('EMERGENCY', 'Emergency Admission'), ('TRANSFER', 'Transfer from Another Hospital')], default='REGULAR', max_length=20)),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('doctor_availability_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('admitting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_patients', to=settings.AUTH_USER_MODEL)),
                ('assigned_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patient.bed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patient.patient')),
            ],
            options={
                'db_table': 'patient_admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('is_on_duty', models.BooleanField(default=True)),
                ('max_patients', models.IntegerField(default=2)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nurses',
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='patient.room'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
