# Generated by Django 4.2.9 on 2025-04-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_bed_room_patientadmission_nurse_bed_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('timing', models.CharField(choices=[('BEFORE_MEAL', 'Before Meal'), ('AFTER_MEAL', 'After Meal'), ('WITH_MEAL', 'With Meal'), ('EMPTY_STOMACH', 'Empty Stomach'), ('BEDTIME', 'At Bedtime'), ('AS_NEEDED', 'As Needed (PRN)')], default='AFTER_MEAL', max_length=15)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once a day'), ('TWICE', 'Twice a day'), ('THRICE', 'Three times a day'), ('FOUR', 'Four times a day'), ('HOURLY_4', 'Every 4 hours'), ('HOURLY_6', 'Every 6 hours'), ('HOURLY_8', 'Every 8 hours'), ('HOURLY_12', 'Every 12 hours'), ('WEEKLY', 'Once a week'), ('MONTHLY', 'Once a month'), ('AS_DIRECTED', 'As directed')], default='THRICE', max_length=15)),
                ('duration', models.PositiveIntegerField(default=7)),
                ('duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.medicalrecord')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['id'],
            },
        ),
    ]
