# Generated by Django 5.2 on 2025-06-26 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis', models.TextField()),
                ('secondary_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField()),
                ('estimated_length_of_stay', models.PositiveIntegerField(help_text='Estimated days')),
                ('preferred_room_type', models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Room with TV'), ('LUXURY', 'Luxury Large Room'), ('ICU', 'ICU Room'), ('SUITE', 'Executive Suite')], default='STANDARD', max_length=20)),
                ('preferred_floor', models.IntegerField(blank=True, choices=[(1, 'Floor 1'), (2, 'Floor 2'), (3, 'Floor 3'), (4, 'Floor 4'), (5, 'Floor 5'), (6, 'Floor 6')], null=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special room or care requirements')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved - Awaiting Room Assignment'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed - Patient Admitted')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical/Emergency')], default='MEDIUM', max_length=10)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admission_requests',
                'ordering': ['-created_at', 'priority'],
            },
        ),
        migrations.RenameField(
            model_name='patientadmission',
            old_name='diagnosis',
            new_name='primary_diagnosis',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='specialization',
        ),
        migrations.AddField(
            model_name='bed',
            name='is_functional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='maintenance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nurse',
            name='assigned_floors',
            field=models.JSONField(default=list, help_text='List of floor numbers assigned to this nurse'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='estimated_discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='secondary_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.CharField(choices=[('GENERAL_MEDICINE', 'General Medicine'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPEDIC', 'Orthopedic'), ('NEUROLOGY', 'Neurology'), ('ONCOLOGY', 'Oncology'), ('EMERGENCY', 'Emergency')], default='GENERAL_MEDICINE', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_cleaned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Room with TV'), ('LUXURY', 'Luxury Large Room'), ('ICU', 'ICU Room'), ('SUITE', 'Executive Suite')], default='STANDARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='max_patients',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='admission_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Admission'), ('EMERGENCY', 'Emergency Admission'), ('TRANSFER', 'Transfer from Another Hospital'), ('SCHEDULED', 'Scheduled Surgery/Procedure')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(choices=[(1, 'Floor 1'), (2, 'Floor 2'), (3, 'Floor 3'), (4, 'Floor 4'), (5, 'Floor 5'), (6, 'Floor 6')]),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['admission_date', 'discharge_date'], name='patient_adm_admissi_06bf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['bed', 'discharge_date'], name='patient_adm_bed_id_0c4bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor', 'room_type'], name='rooms_floor_1c92f7_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_occupied', 'room_type'], name='rooms_is_occu_053a21_idx'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requests', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='patient_admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_request', to='patient.patientadmission'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='requesting_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admission_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
