# Generated by Django 5.2 on 2025-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_admissionrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(choices=[('GENERAL_MEDICINE', 'General Medicine Nursing'), ('CARDIOLOGY', 'Cardiac Nursing'), ('ORTHOPEDIC', 'Orthopedic Nursing'), ('NEUROLOGY', 'Neurological Nursing'), ('ONCOLOGY', 'Oncology Nursing'), ('EMERGENCY', 'Emergency & Critical Care'), ('GENERAL_NURSING', 'General Nursing')], default='GENERAL_NURSING', help_text='Primary specialization of the nurse', max_length=20),
        ),
    ]
