# Generated by Django 5.2 on 2025-06-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_update_nurse_floor_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequest',
            name='preferred_room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Room with TV'), ('LUXURY', 'Luxury Large Room'), ('ICU', 'ICU Room'), ('SUITE', 'Executive Suite'), ('OPERATION_ROOM', 'Operation Theater')], default='STANDARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Room with TV'), ('LUXURY', 'Luxury Large Room'), ('ICU', 'ICU Room'), ('SUITE', 'Executive Suite'), ('OPERATION_ROOM', 'Operation Theater')], default='STANDARD', max_length=20),
        ),
    ]
